" Look and feel
syntax on
set number
map j gj
map k gk
set timeoutlen=1000 ttimeoutlen=0

" Solarized
set nocompatible
set t_Co=16
"let g:solarized_termcolors=256
call pathogen#infect()
set background=dark " dark | light "
colorscheme solarized
call togglebg#map("<F5>")

"set cursorline
set colorcolumn=80

" Indentation
filetype plugin on
filetype indent on
set tabstop=4
set shiftwidth=4
set expandtab
"" Filetype specific indentation
autocmd Filetype c setlocal tabstop=8 shiftwidth=8
autocmd Filetype h setlocal tabstop=8 shiftwidth=8

" Multi-editor stuff
"" Tabbing
map <C-l> :tabn<CR>
map <C-h> :tabp<CR>
map <C-n> :tabnew<CR>
map <C-x> :tabclose<CR>
"" Windows
map <TAB> <C-W>w
map <S-TAB> <C-W>W
map <C-t> :NERDTreeToggle<CR>

" Search stuff
map <C-g> :FufCoverageFile<CR>

call pathogen#incubate()
call pathogen#helptags()

runtime source/backup
