" Look and feel
syntax on
set number
map j gj
map k gk
set timeoutlen=1000 ttimeoutlen=0
"" Working with source control
set autoread

" Solarized
set nocompatible
set t_Co=16
"let g:solarized_termcolors=256
call pathogen#infect()
set background=dark " dark | light "
colorscheme solarized
call togglebg#map("<F5>")

"set cursorline
set colorcolumn=80

" Indentation
filetype plugin on
filetype indent on
set tabstop=4
set shiftwidth=4
set expandtab
"" Filetype specific indentation
autocmd Filetype c setlocal tabstop=8 shiftwidth=8
autocmd Filetype h setlocal tabstop=8 shiftwidth=8
autocmd Filetype html setlocal tabstop=2 shiftwidth=2
autocmd Filetype javascript setlocal tabstop=2 shiftwidth=2
autocmd Filetype go setlocal noexpandtab

" vim-go
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_fields = 1
let g:go_highlight_types = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
let g:neocomplete#enable_at_startup = 1

" Multi-editor stuff
"" Tabbing
map <C-l> :tabn<CR>
map <C-h> :tabp<CR>
map <C-n> :tabnew<CR>
map <C-x> :tabclose<CR>
"" Windows
map <TAB> <C-W>w
map <S-TAB> <C-W>W
map <Left> :vertical resize -5<CR>
map <Right> :vertical resize +5<CR>
map <Down> :resize -5<CR>
map <Up> :resize +5<CR>
map <C-t> :NERDTreeToggle<CR>

" Search stuff
map <C-g> :FufCoverageFile<CR>
let g:fuf_coveragefile_exclude = '\v\~$|(^|[/\\])(node_modules)'

call pathogen#infect('bundle/{}')
call pathogen#helptags()

runtime source/backup
