# Shell is non-interactive.  Be done now!
if [[ $- != *i* ]] ; then return; fi

# Find current dir, even if symlinked.
# https://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-
# directory-its-stored-in/
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
    BASHDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$BASHDIR/$SOURCE"
done
BASHDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
export BASHDIR
export DOTFILESDIR="$( cd -P "${BASHDIR}/.." && pwd )"

eval `dircolors ${BASHDIR}/dircolors-solarized/dircolors.ansi-dark`

export EDITOR=vim
export SOLARIZED=true
export TERM="screen-256color"
export LESSOPEN="| source-highlight-esc.sh %s"
export LESS=' -R '

alias mpcp='mpc playlist -f "[%position% %artist% - %title%]"'
alias tmux="tmux -2"
alias valgrinda="valgrind --track-origins=yes --leak-check=full"

if [ -f $BASHDIR/bashrc.local ]; then
    source $BASHDIR/bashrc.local
fi
