# Shell is non-interactive.  Be done now!
if [[ $- != *i* ]] ; then return; fi

# Find current dir, even if symlinked.
# https://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-
# directory-its-stored-in/
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
    BASHDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$BASHDIR/$SOURCE"
done
BASHDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
export BASHDIR
export DOTFILESDIR="$( cd -P "${BASHDIR}/.." && pwd )"

export EDITOR=vim
export LESS=' -R '

if [ -f $BASHDIR/bashrc.local ]; then
    source $BASHDIR/bashrc.local
fi
